import one from "../assets/QQQ.jpg";
import two from "../assets/contactfaruq.jpg";
import residential1 from "../assets/latest1.jpg"
import residential2 from "../assets/residential2.jpg"
import residential3 from "../assets/latest3.jpg"
import latest2 from "../assets/latest2.jpg"
import newresidence from "../assets/newresidence.jpg"
import newresidence2 from "../assets/aboutImage.jpeg"




export const projectlist = [
    {
        id: 1,

        title: "All Projects",
        images: [
            {
                id: 11,
                src: residential1,
                title: "Title 1",
                desc: "Description 1",
                mainimage: residential1,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 12,
                src: one,
                title: "Title 2",
                desc: "Description 2",
                mainimage: one,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 13,
                src: residential2,
                title: "Title 3",
                desc: "Description 3",
                mainimage: residential2,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            }, {
                id: 14,
                src: latest2,
                title: "Title 4",
                desc: "Description 4",
                mainimage: latest2,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 15,
                src: newresidence2,
                title: "Title 5",
                desc: "Description 5",
                mainimage: newresidence2,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 16,
                src: residential3,
                title: "Title 6",
                desc: "Description 6",
                mainimage: residential3,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 17,
                src: newresidence,
                title: "Title 7",
                desc: "Description 7",
                mainimage: newresidence,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },],
    },
    {
        id: 2,
        title: "Residential",
        images: [
            {
                id: 21,
                src: residential1,
                title: "Title 1",
                desc: "Description 1",
                mainimage: residential1,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 22,
                src: one,
                title: "Title 2",
                desc: "Description 2",
                mainimage: one,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 23,
                src: residential2,
                title: "Title 3",
                desc: "Description 3",
                mainimage: residential2,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            }, {
                id: 24,
                src: latest2,
                title: "Title 4",
                desc: "Description 4",
                mainimage: latest2,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 25,
                src: newresidence2,
                title: "Title 5",
                desc: "Description 5",
                mainimage: newresidence2,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 26,
                src: residential3,
                title: "Title 6",
                desc: "Description 6",
                mainimage: residential3,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 27,
                src: newresidence,
                title: "Title 7",
                desc: "Description 7",
                mainimage: newresidence,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },]
    },
    {
        id: 3,
        title: "Commercial",
        images: [
            {
                id: 31,
                src: one, title: "Title 1", desc: "Description 1", mainimage: one,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 32,
                src: one, title: "Title 1", desc: "Description 1", mainimage: one,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 33,
                src: one, title: "Title 1", desc: "Description 1", mainimage: one,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
            {
                id: 34,
                src: one, title: "Title 1", desc: "Description 1", mainimage: one,
                subimage1: one,
                subimage2: one,
                point1: "Location: 1234 Elm Street, Greenfield, CA",
                point2: "Architectural Style: Modern Contemporary",
                point3: "Square Footage: 3, 500 sq.ft.",
                point4: "Budget: $750,000",
            },
        ],
    },
];
